name: 'analytics_project'
version: '1.0.0'
config-version: 2
profile: analytics_project

model-paths: ["models"]

models:
  analytics_project:
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver"]
    gold:
      +materialized: dynamic_table
      +schema: gold
      +snowflake_warehouse: COMPUTE_WH  # Replace with your warehouse name
      +target_lag: '5 minutes'