# Project
name: dbt_try
version: "1.0"
config-version: 2
profile: dbt_try

vars:
  file_format_name: 'ff_ecomm_customer'

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

on-run-start:
  - "{{ ff_stage_ecomm_customer ('DBT.ECOMM.ECOMM_STAGE_CUSTOMER')}}"

## Target
## target-path: scripts
## clean-targets: [scripts, dbt_modules]

models:
  dbt_try: # this matches the `name:`` config
    +materialized: view 
    marts:
      +materialized: table      
      customer:
        +schema: customer     

        