analytics_project:  
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN  
      database: ANALYTICS_DB
      warehouse: COMPUTE_WH
      schema: silver
      threads: 4   