CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_DB.SILVER.STG_ORDERS
    TARGET_LAG = '1 minutes'
    refresh_mode='INCREMENTAL'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    TO_DATE(ORDER_DATE, 'YYYY-MM-DD') AS ORDER_DATE,
    CAST(NULLIF(AMOUNT, '') AS NUMBER) AS AMOUNT,
    UPPER(STATUS) AS STATUS
FROM ANALYTICS_DB.BRONZE.RAW_ORDERS
WHERE ORDER_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ORDER_ID 
    ORDER BY ORDER_DATE DESC  -- Or any column that indicates recency (e.g., event_ts, ingestion_ts)
) = 1


