CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_DB.SILVER.STG_CUSTOMERS
    TARGET_LAG = '1 minutes'
    refresh_mode='INCREMENTAL'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CASE 
        WHEN EMAIL LIKE '%@%.%' THEN EMAIL 
        ELSE NULL 
    END AS EMAIL,
    TO_DATE(SIGNUP_DATE, 'YYYY-MM-DD') AS SIGNUP_DATE
FROM ANALYTICS_DB.BRONZE.RAW_CUSTOMERS;







