use dbt;
ALTER STAGE DBT.ECOMM.ECOMM_STAGE_CUSTOMER SET DIRECTORY = (ENABLE = true);
CREATE STREAM ECOMM_STAGE_CUSTOMER_STREAM ON STAGE DBT.ECOMM.ECOMM_STAGE_CUSTOMER;


select SYSTEM$STREAM_HAS_DATA('ECOMM_STAGE_CUSTOMER_STREAM')
SELECT
    $1,$2,$3,$4     
FROM @DBT.ECOMM.ECOMM_STAGE_CUSTOMER

SELECT * FROM DBT.ECOMM.CUSTOMER_RAW
TRUNCATE TABLE DBT.ECOMM.CUSTOMER_RAW


ALTER STAGE DBT.ECOMM.ECOMM_STAGE_CUSTOMER REFRESH;

COPY INTO DBT.ECOMM.CUSTOMER_RAW
FROM @DBT.ECOMM.ECOMM_STAGE_CUSTOMER
FILE_FORMAT = DBT.ECOMM.ECOMM_STAGE_CUSTOMER
PURGE = TRUE; -- Automatically deletes files after a successful load

REMOVE @dbt.ecomm.ecomm_stage_customer PATTERN='.*\.*.*';
REMOVE @dbt.ecomm.ecomm_stage_customer PATTERN='.*customers.*';   -- catches .gz, .gzmd5, .gzpart, etc.
ALTER STAGE dbt.ecomm.ecomm_stage_customer REFRESH;
LIST @dbt.ecomm.ecomm_stage_customer;